# Generated by Django 3.1.2 on 2021-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210410_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulluser',
            name='address_1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='fulluser',
            name='address_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='fulluser',
            name='city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='fulluser',
            name='education',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='fulluser',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='fulluser',
            name='employment',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='fulluser',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='fulluser',
            name='state',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='travel',
            name='dest_city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='travel',
            name='dest_state',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='travel',
            name='source_city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='travel',
            name='source_state',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
